[package]
name = "cardinal-reward-distributor"
<<<<<<< HEAD
version = "1.16.0"
=======
version = "1.13.0"
>>>>>>> dfd369d (bump version)
description = "Cardinal reward distributor"
edition = "2021"
homepage = "https://cardinal.so"
repository = "https://github.com/cardinal-labs/cardinal-staking/tree/main/programs/cardinal-reward-distributor"
authors = ["Giannis Chatziveroglou <giannis@cardinal.so>"]
license = "AGPL-3.0"
keywords = ["solana", "cardinal", "stake", "pool"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cardinal_reward_distributor"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
<<<<<<< HEAD
anchor-lang = { version = "0.25.0", features = ["init-if-needed"] }
anchor-spl = "0.25.0"
solana-program = "=1.10.29"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
cardinal-stake-pool = { version = "^1.16.0", path = "../cardinal-stake-pool", features = ["cpi"] }
=======
anchor-lang = { version = "0.24.2", features = ["init-if-needed"] }
anchor-spl = "0.24.2"
solana-program = "1.8.1"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
cardinal-stake-pool = { version = "^1.13.0", path = "../cardinal-stake-pool", features = ["cpi"] }
>>>>>>> dfd369d (bump version)

[dev-dependencies]
proptest = { version = "1.0" }
